package com.eventaccess.platform.domain;

public final class Enums {
    private Enums() {}
    public enum OrganizationStatus { ACTIVE, SUSPENDED, INACTIVE }
    public enum UserStatus { ACTIVE, BLOCKED, PENDING_ACTIVATION, INACTIVE }
    public enum Role { SUPER_ADMIN, ORGANIZER_ADMIN, EVENT_MANAGER, DOOR_STAFF, FINANCE, VIEWER }
    public enum EventStatus { DRAFT, PUBLISHED, SALES_OPEN, SALES_CLOSED, IN_PROGRESS, FINISHED, CANCELED }
    public enum TicketTypeStatus { DRAFT, ACTIVE, SOLD_OUT, PAUSED, CLOSED, CANCELED }
    public enum OrderStatus { PENDING_PAYMENT, PAID, PAYMENT_FAILED, EXPIRED, CANCELED, PARTIALLY_REFUNDED, REFUNDED }
    public enum OrderSource { ONLINE_CHECKOUT, ADMIN, DOOR_SALE, INVITATION }
    public enum PaymentStatus { CREATED, PENDING, APPROVED, FAILED, CANCELED, EXPIRED, PARTIALLY_REFUNDED, REFUNDED }
    public enum TicketStatus { PENDING_PAYMENT, VALID, USED, BLOCKED, CANCELED, REFUNDED, EXPIRED }
    public enum InvitationStatus { PENDING, ACCEPTED, EXPIRED, CANCELED }
    public enum RefundStatus { REQUESTED, PROCESSING, APPROVED, FAILED, CANCELED }
    public enum CheckinResult { APPROVED, ALREADY_USED, INVALID_QR_CODE, WRONG_EVENT, PAYMENT_PENDING, BLOCKED, CANCELED, REFUNDED, EXPIRED, EVENT_NOT_STARTED, EVENT_FINISHED, MANUAL_DENIAL }
}
